### ISSUE TITLE
[BUG]: Removal gem from rubygems

### ISSUE THREAD

**Issue by shingara** [getlago/lago-ruby-client#94]
All non pre version from Rubygems was removed.

Why this removal ?

Can you get back ?

Thanks

**Comment by jdenquin** [comment]
those versions are deprecated and were used as default versions by `rubygems`, this is not something we want to because those version are really old, you can now use https://rubygems.org/gems/lago-ruby-client/versions/0.29.1.pre.beta.
We'll not remove those versions.

The only way we had to fix this usage by default was to remove the really old version with old versioning
